### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by bararchy** [dorkrawk/grey_matter#1]
Hi :) 

Would you mind adding some basic usage examples ?

**Comment by bararchy** [comment]
I started working on my own NeuralNet but if you know what you're doing & actively maintain this then I'll use yours and contribute here

**Comment by dorkrawk** [comment]
Sure I can add some examples soon. This is still VERY MUCH a work in progress. I'm only part way through the back prop implementation right now. But I like Crystal and it's fun to build new libraries so I'd like to keep up with this project.

**Comment by bararchy** [comment]
Cool , if so I'll try and focus my contributions here so we can have a single project which actually does something instead of 100 projects around half made :)

**Comment by dorkrawk** [comment]
I don't want to discourage you from working on neural networks or Crystal. I'm happy to take PRs when this project is in a more usable state but I don't want to slow down anyone else's development while I get things off the ground.
